# Generated by Django 3.1.5 on 2021-01-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20210119_1541'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trains',
            new_name='Train',
        ),
    ]
