# Generated by Django 3.1.5 on 2021-01-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0002_auto_20210120_1711'),
        ('cities', '0002_auto_20210119_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Number of Train')),
                ('travel_times', models.PositiveSmallIntegerField(verbose_name='Total Travel Time')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_city_from_set', to='cities.city', verbose_name='from which city')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_city_to_set', to='cities.city', verbose_name='to which city')),
                ('trains', models.ManyToManyField(to='trains.Train', verbose_name='Train List')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['travel_times'],
            },
        ),
    ]
